---
spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/cognizant?useSSL=false&serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    regisyter-with-eureka: true
    fetch-registry: true
restaurant:
  application:
    name: RESTAURANT-SERVICE
    uri: /restaurant/orders/status/

resilience4j.circuitbreaker:
  instances:
    EmpAPI:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      eventConsumerBufferSize: 10

resilience4j.timelimiter:
  instances:
    EmpAPI:
      timeoutDuration: 2s
      cancelRunningFuture: true

resilience4j.thread-pool-bulkhead:
  instances:
    EmpAPI:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1



